### ISSUE TITLE
WS-2021-0419 - gson vulnerability 

### ISSUE THREAD

**Issue by caiosales** [IBM/secrets-manager-java-sdk#28]
Hi secrets-manager-1.0.2 has a dependency to sdk-core-9.13.3 that uses gson-2.8.7 library

This last library has a know vulnerability:
Denial of Service vulnerability was discovered in gson before 2.8.9 via the writeReplace() method.

Publish Date: 2021-10-11

URL: [WS-2021-0419](https://github.com/google/gson/pull/1991)

SDK-core 9.15.2 already fixed that.

Best Regards

**Comment by IdanAdar** [comment]
Sorry for the late response. Now using `sdk-core-version>9.16.1</sdk-core-version>`.
